version: "3"
services:
  test:
    container_name: test
    build: .
    volumes:
      - .:/src
    ports:
      - 8081:8081
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redislabs/redistimeseries
    restart: always
