version: "3"
services:
  app:
    container_name: app
    build: .
    volumes:
      - .:/src
    ports:
      - 8081:8081
    depends_on:
      - redis
    command: ["./run_app.sh"]

  test:
    container_name: test
    build: .
    volumes:
      - .:/src
    depends_on:
      - redis
    command: ["pytest"]

  redis:
    container_name: redis
    image: redislabs/redistimeseries
